- hosts: windows
  tasks:
  - name: Create directory structure
    win_file:
       path: C:\apps
       state: directory
  - name: create a new application pool in 'Started' state
    win_iis_webapppool:
       name: apps
       state: started
  - name: apps IIS site
    win_iis_website:
       name: apps
       state: started
       port: 80
       hostname: www.mysite.com
       application_pool: apps
       physical_path: C:\apps
       parameters: logfile.directory:C:\apps\logs
       register: website
  - name: copy html
    win_copy:
       src: ./files/Default.htm
       dest: c:\apps\Default.htm

