---
- hosts: linux
  remote_user: vagrant
  become: true
  
  tasks:
  - name: install epel
    yum: name=epel-release state=present
  - name: install nginx
    yum: name=nginx state=installed update_cache=true
    notify:
      - start nginx

  handlers:
  - name: restart nginx
    service: 
      name: nginx
      state: restarted
  - name: reload nginx
    service: 
      name: nginx
      state: reloaded
  - name: start nginx
    service:
      name: nginx
      state: started
      enabled: yes   

